# Generated by Django 2.2.17 on 2021-01-27 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electricNOVA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=100)),
                ('poblacion', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Electrocasero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('cp', models.CharField(max_length=5)),
                ('direccion', models.CharField(max_length=100)),
                ('poblacion', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=50)),
                ('preciodecarga', models.DecimalField(decimal_places=2, max_digits=5)),
                ('horasdisponibles', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electricNOVA.Cliente')),
                ('electrocasero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electricNOVA.Electrocasero')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electricNOVA.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='TipoCargador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='electrocasero',
            name='tiposCargador',
            field=models.ManyToManyField(to='electricNOVA.TipoCargador'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='reservas',
            field=models.ManyToManyField(through='electricNOVA.Reserva', to='electricNOVA.Electrocasero'),
        ),
    ]
